[package]
name = "core_financiero"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
domain = { path = "../domain" }
uniffi = { workspace = true, features = ["cli"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
